apiVersion: v1
kind: pod 
metadata:
        name: image
        label: ngnix
spec:
        containers: 
          - name: ngnix
            image: ngnix
            ports: 
             - containerPort: 80

